//Sign In'
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_FAILED = 'SIGN_UP_USER_FAILED';
export const SIGN_UP_USER_NETWORK_ERROR = 'SIGN_UP_USER_NETWORK_ERROR';
export const LOADING_SIGN_UP_USER = 'LOADING_SIGN_UP_USER';
export const RESET_SIGN_UP_USER = 'RESET_SIGN_UP_USER';

//Login
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOADING_LOGIN_USER = 'LOADING_LOGIN_USER';
export const LOGIN_USER_NETWORK_ERROR = 'LOGIN_USER_NETWORK_ERROR';
export const RESET_LOGIN_USER = 'RESET_LOGIN_USER';

//Sign Out
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED';
export const LOADING_LOGOUT_USER = 'LOADING_LOGOUT_USER';
export const LOGOUT_USER_NETWORK_ERROR = 'LOGOUT_USER_NETWORK_ERROR';
export const RESET_LOGOUT_USER = 'RESET_LOGOUT_USER';

//Get Products
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';
export const LOADING_GET_PRODUCT = 'LOADING_GET_PRODUCT';
export const GET_PRODUCT_NETWORK_ERROR = 'GET_PRODUCT_NETWORK_ERROR';
export const RESET_GET_PRODUCT = 'RESET_GET_PRODUCT';
//Add product
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';
export const ADD_PRODUCT_NETWORK_ERROR = 'ADD_PRODUCT_NETWORK_ERROR';
export const LOADING_ADD_PRODUCT = 'LOADING_ADD_PRODUCT';
export const RESET_ADD_PRODUCT = 'RESET_ADD_PRODUCT';
//Update Product
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';
export const UPDATE_PRODUCT_NETWORK_ERROR = 'UPDATE_PRODUCT_NETWORK_ERROR';
export const LOADING_UPDATE_PRODUCT = 'LOADING_UPDATE_PRODUCT';
export const RESET_UPDATE_PRODUCT = 'RESET_UPDATE_PRODUCT';
//Delete Product

//Get Orders
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';
export const LOADING_GET_ORDER = 'LOADING_GET_ORDER';
export const GET_ORDER_NETWORK_ERROR = 'GET_ORDER_NETWORK_ERROR';
export const RESET_GET_ORDER = 'RESET_GET_ORDER';
//Add Order
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAILED = 'ADD_ORDER_FAILED';
export const LOADING_ADD_ORDER = 'LOADING_ADD_ORDER';
export const ADD_ORDER_NETWORK_ERROR = 'ADD_ORDER_NETWORK_ERROR';
export const RESET_ADD_ORDER = 'RESET_ADD_ORDER';
